name: CI - Unit and Live Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  unit-tests:
    name: PHP Unit Tests
    runs-on: ubuntu-latest
    env:
      QLTY_TOKEN: ${{ secrets.QLTY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP (with Xdebug for coverage)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          tools: composer

      - name: Validate composer.json
        run: composer validate --no-check-lock

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Prepare coverage directory
        run: mkdir -p build/logs

      - name: Run Unit tests with coverage (Clover)
        run: vendor/bin/phpunit --testsuite Unit --colors=always --coverage-clover build/logs/clover.xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: clover-coverage
          path: build/logs/clover.xml

      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{secrets.QLTY_TOKEN}}
          files: build/logs/clover.xml

  integration-tests:
    name: PHP Integration (Live ENS) Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      ENS_PROVIDER_URL: ${{ secrets.ENS_PROVIDER_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Validate composer.json
        run: composer validate --no-check-lock

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run live integration tests
        run: vendor/bin/phpunit --testsuite Integration --colors=always
